name: Flower Shop CI

on: [push, pull_request]

jobs:
  job_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsqlite3-dev libgtest-dev lcov
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build
      run: cmake -S flowers_shop -B build && cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate Report
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' '*/build/*' --output-file coverage.info
        genhtml coverage.info --output-directory out_report

    - name: Save Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html
        path: out_report/
