name: Flower Shop CI

on: [push, pull_request]

jobs:
  job_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsqlite3-dev libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Configure CMake
      run: cmake -S flowers_shop -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
